//AgreementStyles.ts
import { StyleSheet, useColorScheme } from "react-native";

const dark = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  gradientOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
    backgroundColor: 'rgba(12, 17, 24, 0.9)',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(141, 163, 176, 0.3)',
  },
  backButtonText: {
    color: '#8DA3B0',
    fontSize: 16,
    fontWeight: '600',
  },
  content: {
    flex: 1,
    paddingTop: 90,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 60,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 40,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(141, 163, 176, 0.2)',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 32,
    color: '#8DA3B0',
    fontWeight: 'bold',
    letterSpacing: 2,
    textAlign: 'center',
    textShadowColor: 'rgba(141, 163, 176, 0.3)',
    textShadowRadius: 3,
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#B8C5D1',
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '500',
  },
  divider: {
    width: 80,
    height: 3,
    backgroundColor: '#8DA3B0',
    marginTop: 15,
    borderRadius: 2,
  },
  documentCard: {
    backgroundColor: 'rgba(12, 17, 24, 0.85)',
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(141, 163, 176, 0.2)',
    shadowColor: '#8DA3B0',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  sectionTitle: {
    fontSize: 22,
    color: '#8DA3B0',
    fontWeight: 'bold',
    marginBottom: 16,
    letterSpacing: 1,
    textAlign: 'center',
  },
  sectionNumber: {
    fontSize: 20,
    color: '#8DA3B0',
    fontWeight: 'bold',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  sectionContent: {
    marginBottom: 20,
  },
  paragraphText: {
    fontSize: 15,
    color: '#E2E8F0',
    lineHeight: 24,
    marginBottom: 12,
    fontWeight: '400',
    textAlign: 'justify',
  },
  bulletPoint: {
    fontSize: 15,
    color: '#E2E8F0',
    lineHeight: 22,
    marginBottom: 8,
    marginLeft: 16,
    fontWeight: '400',
  },
  highlightText: {
    color: '#8DA3B0',
    fontWeight: '600',
  },
  importantNotice: {
    backgroundColor: 'rgba(141, 163, 176, 0.15)',
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#8DA3B0',
    marginVertical: 16,
  },
  importantText: {
    fontSize: 14,
    color: '#F1F5F9',
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  consentSection: {
    backgroundColor: 'rgba(141, 163, 176, 0.1)',
    padding: 20,
    borderRadius: 12,
    marginTop: 20,
    borderWidth: 2,
    borderColor: 'rgba(141, 163, 176, 0.3)',
  },
  consentTitle: {
    fontSize: 18,
    color: '#8DA3B0',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: 1,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    paddingHorizontal: 8,
  },
  agreeButton: {
    backgroundColor: '#8DA3B0',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 28,
    flex: 1,
    marginRight: 8,
    shadowColor: '#8DA3B0',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  viewPolicyButton: {
    backgroundColor: 'rgba(141, 163, 176, 0.2)',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 28,
    flex: 1,
    marginLeft: 8,
    borderWidth: 1,
    borderColor: 'rgba(141, 163, 176, 0.4)',
  },
  agreeButtonText: {
    color: '#0c1118',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  viewPolicyButtonText: {
    color: '#8DA3B0',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  contactInfo: {
    backgroundColor: 'rgba(12, 17, 24, 0.9)',
    padding: 20,
    borderRadius: 12,
    marginTop: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(141, 163, 176, 0.2)',
  },
  contactTitle: {
    fontSize: 16,
    color: '#8DA3B0',
    fontWeight: 'bold',
    marginBottom: 8,
  },
  contactText: {
    fontSize: 14,
    color: '#B8C5D1',
    textAlign: 'center',
  },
  emailText: {
    color: '#007AFF',
    textDecorationLine: 'underline',
    textDecorationColor:'#007AFF',
    fontWeight: '600',
  },
  dataList: {
    backgroundColor: 'rgba(141, 163, 176, 0.05)',
    padding: 16,
    borderRadius: 10,
    marginVertical: 12,
  },
  dataListItem: {
    fontSize: 14,
    color: '#E2E8F0',
    lineHeight: 20,
    marginBottom: 6,
    paddingLeft: 8,
  },
  rightsCard: {
    backgroundColor: 'rgba(141, 163, 176, 0.08)',
    padding: 18,
    borderRadius: 12,
    marginVertical: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#8DA3B0',
  },
  rightItem: {
    fontSize: 14,
    color: '#E2E8F0',
    lineHeight: 20,
    marginBottom: 8,
    paddingLeft: 6,
  },
  legalText: {
    fontSize: 13,
    color: '#94A3B8',
    lineHeight: 20,
    textAlign: 'justify',
    fontStyle: 'italic',
    marginTop: 8,
  },
  bottomSpacing: {
    height: 40,
  },
});


const light = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  gradientOverlay: {
    display: 'none',
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  backButtonText: {
    color: '#005F99',
    fontSize: 16,
    fontWeight: '600',
  },
  content: {
    flex: 1,
    paddingTop: 90,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 60,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 40,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(59, 130, 246, 0.2)',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 32,
    color: '#005F99',
    fontWeight: 'bold',
    letterSpacing: 2,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 95, 153, 0.1)',
    textShadowRadius: 1,
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#4B5563',
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '500',
  },
  divider: {
    width: 80,
    height: 3,
    backgroundColor: '#005F99',
    marginTop: 15,
    borderRadius: 2,
  },
  documentCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 22,
    color: '#005F99',
    fontWeight: 'bold',
    marginBottom: 16,
    letterSpacing: 1,
    textAlign: 'center',
  },
  sectionNumber: {
    fontSize: 20,
    color: '#005F99',
    fontWeight: 'bold',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  sectionContent: {
    marginBottom: 20,
  },
  paragraphText: {
    fontSize: 15,
    color: '#1F2937',
    lineHeight: 24,
    marginBottom: 12,
    fontWeight: '400',
    textAlign: 'justify',
  },
  bulletPoint: {
    fontSize: 15,
    color: '#1F2937',
    lineHeight: 22,
    marginBottom: 8,
    marginLeft: 16,
    fontWeight: '400',
  },
  highlightText: {
    color: '#005F99',
    fontWeight: '600',
  },
  importantNotice: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
    marginVertical: 16,
  },
  importantText: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  consentSection: {
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
    padding: 20,
    borderRadius: 12,
    marginTop: 20,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  consentTitle: {
    fontSize: 18,
    color: '#005F99',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: 1,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    paddingHorizontal: 8,
  },
  agreeButton: {
    backgroundColor: '#3B82F6',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 28,
    flex: 1,
    marginRight: 8,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  viewPolicyButton: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 28,
    flex: 1,
    marginLeft: 8,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.4)',
  },
  agreeButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  viewPolicyButtonText: {
    color: '#005F99',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  contactInfo: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 20,
    borderRadius: 12,
    marginTop: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 4,
  },
  contactTitle: {
    fontSize: 16,
    color: '#005F99',
    fontWeight: 'bold',
    marginBottom: 8,
  },
  contactText: {
    fontSize: 14,
    color: '#4B5563',
    textAlign: 'center',
  },
  emailText: {
    color: '#007AFF',
    textDecorationLine: 'underline',
    textDecorationColor:'#007AFF',
    fontWeight: '600',
  },
  dataList: {
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
    padding: 16,
    borderRadius: 10,
    marginVertical: 12,
  },
  dataListItem: {
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 20,
    marginBottom: 6,
    paddingLeft: 8,
  },
  rightsCard: {
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
    padding: 18,
    borderRadius: 12,
    marginVertical: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#3B82F6',
  },
  rightItem: {
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 20,
    marginBottom: 8,
    paddingLeft: 6,
  },
  legalText: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 20,
    textAlign: 'justify',
    fontStyle: 'italic',
    marginTop: 8,
  },
  bottomSpacing: {
    height: 40,
  },
});

const useThemedStyles = () => {
  const colorScheme = useColorScheme();
  return colorScheme === "dark" ? dark : light;
};

export default useThemedStyles;