//AboutUs.tsx
import { StyleSheet, useColorScheme } from "react-native";

const dark = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  gradientOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
    backgroundColor: 'rgba(12, 17, 24, 0.8)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  backButtonText: {
    color: '#8DA3B0',
    fontSize: 16,
    fontWeight: '500',
  },
  content: {
    flex: 1,
    paddingTop: 80,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 30,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 15,
  },
  headerTitle: {
    fontSize: 36,
    color: '#8DA3B0',
    fontWeight: 'bold',
    letterSpacing: 3,
    textAlign: 'center',
    textShadowColor: 'rgba(141, 163, 176, 0.3)',
    textShadowRadius: 2,
  },
  divider: {
    width: 60,
    height: 3,
    backgroundColor: '#8DA3B0',
    marginTop: 10,
    borderRadius: 2,
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 24,
    color: '#8DA3B0',
    fontWeight: 'bold',
    marginBottom: 15,
    letterSpacing: 1,
  },
  missionCard: {
    backgroundColor: 'rgba(12, 17, 24, 0.8)',
    padding: 20,
    borderRadius: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#8DA3B0',
  },
  missionText: {
    fontSize: 16,
    color: '#E2E8F0',
    lineHeight: 24,
    marginBottom: 12,
    fontWeight: '500',
  },
  missionSubtext: {
    fontSize: 15,
    color: '#B8C5D1',
    lineHeight: 22,
  },
  featureCard: {
    flexDirection: 'row',
    backgroundColor: 'rgba(12, 17, 24, 0.7)',
    padding: 18,
    borderRadius: 12,
    marginBottom: 15,
    alignItems: 'flex-start',
  },
  featureIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(141, 163, 176, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  iconText: {
    fontSize: 20,
  },
  featureContent: {
    flex: 1,
  },
  featureTitle: {
    fontSize: 18,
    color: '#8DA3B0',
    fontWeight: 'bold',
    marginBottom: 6,
  },
  featureDescription: {
    fontSize: 14,
    color: '#B8C5D1',
    lineHeight: 20,
  },
  foundersCard: {
    backgroundColor: 'rgba(12, 17, 24, 0.8)',
    padding: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(141, 163, 176, 0.3)',
  },
  foundersText: {
    fontSize: 16,
    color: '#E2E8F0',
    marginBottom: 15,
    fontWeight: '500',
  },
  founderItem: {
    backgroundColor: 'rgba(141, 163, 176, 0.1)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#8DA3B0',
  },
  founderName: {
    fontSize: 16,
    color: '#8DA3B0',
    fontWeight: 'bold',
  },
  foundersDescription: {
    fontSize: 14,
    color: '#B8C5D1',
    lineHeight: 20,
    marginTop: 10,
  },
  visionCard: {
    backgroundColor: 'rgba(141, 163, 176, 0.1)',
    padding: 20,
    borderRadius: 15,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(141, 163, 176, 0.3)',
  },
  visionText: {
    fontSize: 22,
    color: '#8DA3B0',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 12,
    letterSpacing: 1,
  },
  visionDescription: {
    fontSize: 15,
    color: '#E2E8F0',
    textAlign: 'center',
    lineHeight: 22,
  },
  contactSection: {
    alignItems: 'center',
    backgroundColor: 'rgba(12, 17, 24, 0.9)',
    padding: 20,
    borderRadius: 15,
    marginTop: 10,
  },
  contactTitle: {
    fontSize: 20,
    color: '#8DA3B0',
    fontWeight: 'bold',
    marginBottom: 8,
  },
  contactText: {
    fontSize: 14,
    color: '#B8C5D1',
    textAlign: 'center',
    marginBottom: 20,
  },
  contactButton: {
    backgroundColor: '#8DA3B0',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
  },
  contactButtonText: {
    color: '#0c1118',
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomSpacing: {
    height: 20,
  },
});

// Light theme styles
const light = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  gradientOverlay: {
    display: 'none',
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  backButtonText: {
    color: '#005F99',
    fontSize: 16,
    fontWeight: '600',
  },
  content: {
    flex: 1,
    paddingTop: 80,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 30,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 15,
  },
  headerTitle: {
    fontSize: 36,
    color: '#005F99',
    fontWeight: 'bold',
    letterSpacing: 3,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 95, 153, 0.1)',
    textShadowRadius: 1,
  },
  divider: {
    width: 60,
    height: 3,
    backgroundColor: '#005F99',
    marginTop: 10,
    borderRadius: 2,
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 24,
    color: '#005F99',
    fontWeight: 'bold',
    marginBottom: 15,
    letterSpacing: 1,
  },
  missionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 20,
    borderRadius: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  missionText: {
    fontSize: 16,
    color: '#1F2937',
    lineHeight: 24,
    marginBottom: 12,
    fontWeight: '500',
  },
  missionSubtext: {
    fontSize: 15,
    color: '#4B5563',
    lineHeight: 22,
  },
  featureCard: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    padding: 18,
    borderRadius: 12,
    marginBottom: 15,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  featureIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  iconText: {
    fontSize: 20,
  },
  featureContent: {
    flex: 1,
  },
  featureTitle: {
    fontSize: 18,
    color: '#005F99',
    fontWeight: 'bold',
    marginBottom: 6,
  },
  featureDescription: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  foundersCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  foundersText: {
    fontSize: 16,
    color: '#1F2937',
    marginBottom: 15,
    fontWeight: '500',
  },
  founderItem: {
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#3B82F6',
  },
  founderName: {
    fontSize: 16,
    color: '#005F99',
    fontWeight: 'bold',
  },
  foundersDescription: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
    marginTop: 10,
  },
  visionCard: {
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
    padding: 20,
    borderRadius: 15,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  visionText: {
    fontSize: 22,
    color: '#005F99',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 12,
    letterSpacing: 1,
  },
  visionDescription: {
    fontSize: 15,
    color: '#1F2937',
    textAlign: 'center',
    lineHeight: 22,
  },
  contactSection: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 20,
    borderRadius: 15,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 4,
  },
  contactTitle: {
    fontSize: 20,
    color: '#005F99',
    fontWeight: 'bold',
    marginBottom: 8,
  },
  contactText: {
    fontSize: 14,
    color: '#4B5563',
    textAlign: 'center',
    marginBottom: 20,
  },
  contactButton: {
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3.84,
    elevation: 5,
  },
  contactButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomSpacing: {
    height: 20,
  },
});

const useThemedStyles = () => {
  const colorScheme = useColorScheme();
  return colorScheme === "dark" ? dark : light;
};

export default useThemedStyles;