//Login.tsx styles
import { StyleSheet, useColorScheme } from "react-native";

const dark = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
  },
  gradientOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  content: {
    flex: 1,
    paddingHorizontal: 40,
    paddingTop: 60,
    paddingBottom: 36,
  },
  backButton: {
    alignSelf: "flex-start",
    marginBottom: 20,
  },
  backButtonText: {
    color: "#8DA3B0",
    fontSize: 16,
    fontWeight: "500",
  },
  logoContainer: {
    position: "relative",
    left: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  brandName: {
    fontSize: 48,
    color: "#8DA3B0",
    fontWeight: "bold",
    letterSpacing: 2,
    textAlign: "center",
    marginBottom: 10,
  },
  welcomeMessage: {
    fontSize: 24,
    color: "#E2E8F0",
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 18,
    color: "#8DA3B0",
    fontWeight: "400",
    textAlign: "center",
    marginBottom: 24,
  },
  formContainer: {
    flex: 1,
    justifyContent: "center",
  },
  input: {
    backgroundColor: "rgba(12, 17, 24, 0.8)",
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
    fontSize: 16,
    color: "#E2E8F0",
    marginBottom: 16,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(12, 17, 24, 0.8)",
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 12,
    marginBottom: 16,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 18,
    fontSize: 16,
    color: "#E2E8F0",
  },
  showPasswordButton: {
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  showPasswordText: {
    color: "#8DA3B0",
    fontSize: 16,
    fontWeight: "500",
  },
  optionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  rememberContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 4,
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(12, 17, 24, 0.8)",
  },
  checkboxChecked: {
    backgroundColor: "#8DA3B0",
    borderColor: "#8DA3B0",
  },
  checkmark: {
    color: "#000000",
    fontSize: 12,
    fontWeight: "bold",
  },
  rememberText: {
    color: "#E2E8F0",
    fontSize: 14,
  },
  forgotPasswordText: {
    color: "#8DA3B0",
    fontSize: 14,
    fontWeight: "500",
  },
  otpContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 320,
    alignSelf: "center",
    marginBottom: 16,
    paddingHorizontal: 10,
  },
  otpInput: {
    width: 45,
    height: 55,
    backgroundColor: "rgba(12, 17, 24, 0.8)",
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 8,
    fontSize: 20,
    color: "#E2E8F0",
    marginHorizontal: 2,
    fontWeight: "600",
  },
  otpInputDimmed: {
    backgroundColor: "#111827",
    opacity: 0.5,
  },
  otpLabel: {
    color: "#E2E8F0",
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 16,
  },
  resendButton: {
    alignSelf: "center",
    marginBottom: 16,
  },
  resendText: {
    color: "#8DA3B0",
    fontSize: 14,
    fontWeight: "500",
    textDecorationLine: "underline",
  },
  loginButton: {
    backgroundColor: "#0c1118",
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 25,
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#374151",
  },
  loginButtonText: {
    color: "#E2E8F0",
    fontSize: 16,
    fontWeight: "600",
  },
  signupLink: {
    alignItems: "center",
    marginBottom: 12,
  },
  signupLinkText: {
    color: "#8DA3B0",
    fontSize: 14,
    fontWeight: "500",
  },
  alternativeLink: {
    alignItems: "center",
    marginBottom: 20,
  },
  alternativeLinkText: {
    color: "#6B7280",
    fontSize: 14,
    fontWeight: "400",
    textDecorationLine: "underline",
  },
  actionLinksContainer: {
    marginBottom: 10,
  },
  actionLinksRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  actionLinkButton: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: 1,
  },
  actionLinkText: {
    color: "#6B7280",
    fontSize: 11,
    fontWeight: "400",
    textDecorationLine: "underline",
    textAlign: "center",
  },
  alternativeContainer: {
    marginBottom: 20,
  },
  alternativeTitle: {
    color: "#E2E8F0",
    fontSize: 20,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 20,
  },
  methodButton: {
    backgroundColor: "rgba(12, 17, 24, 0.8)",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 12,
  },
  methodButtonIcon: {
    marginRight: 8,
  },
  methodButtonText: {
    color: "#E2E8F0",
    fontSize: 16,
    fontWeight: "600",
  },
  backToLoginButton: {
    alignItems: "center",
    marginTop: 12,
  },
  backToLoginText: {
    color: "#8DA3B0",
    fontSize: 14,
    fontWeight: "500",
    textDecorationLine: "underline",
  },
  forgotTitle: {
    color: "#E2E8F0",
    fontSize: 24,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
  },
  forgotSubtitle: {
    color: "#6B7280",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 24,
  },
  methodOption: {
    backgroundColor: "rgba(12, 17, 24, 0.8)",
    borderWidth: 1,
    borderColor: "#374151",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 12,
  },
  methodOptionSelected: {
    borderColor: "#8DA3B0",
    backgroundColor: "rgba(141, 163, 176, 0.1)",
  },
  methodOptionText: {
    color: "#E2E8F0",
    fontSize: 16,
    fontWeight: "500",
  },
  statusContainer: {
    marginTop: 10,
    alignItems: "center",
  },
  successStatus: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.3)",
  },
  successText: {
    color: "#10B981",
    fontSize: 16,
    fontWeight: "500",
    marginLeft: 8,
  },
  errorStatus: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
    marginBottom: 12,
  },
  errorText: {
    position: "relative",
    bottom: 20,
    color: "#EF4444",
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
  },
  backendErrorText: {
    color: "#EF4444",
    fontSize: 12,
    marginLeft: 8,
    flex: 1,
  },
  proceedSection: {
    marginTop: 30,
    alignItems: "center",
  },
  countdownText: {
    color: "#9CA3AF",
    fontSize: 14,
    textAlign: "center",
  },
  errorInput: {
    borderColor: "#EF4444",
    borderWidth: 1,
  },
  // Compact styles for better spacing
  compactFormContainer: {
    paddingHorizontal: 20,
  },
  compactTitle: {
    fontSize: 20,
    marginBottom: 8,
  },
  compactSubtitle: {
    fontSize: 14,
    marginBottom: 16,
  },
  compactAlternativeContainer: {
    marginBottom: 16,
  },
  compactMethodOption: {
    paddingVertical: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  compactMethodOptionText: {
    fontSize: 14,
  },
  compactDestinationText: {
    fontSize: 12,
    marginBottom: 0,
    textAlign: 'left',
  },
  compactActionLinks: {
    marginTop: 12,
  },
});

// Light theme styles
const light = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  gradientOverlay: {
    display: "none", // No gradient overlay needed for light mode
  },
  content: {
    flex: 1,
    paddingHorizontal: 40,
    paddingTop: 60,
    paddingBottom: 36,
  },
  backButton: {
    alignSelf: "flex-start",
    marginBottom: 20,
  },
  backButtonText: {
    color: "#005F99",
    fontSize: 16,
    fontWeight: "500",
  },
  logoContainer: {
    position: "relative",
    left: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  brandName: {
    fontSize: 48,
    color: "#005F99", // Blue color matching the logo
    fontWeight: "bold",
    letterSpacing: 2,
    textAlign: "center",
    marginBottom: 10,
  },
  welcomeMessage: {
    fontSize: 24,
    color: "#005F99",
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 18,
    color: "#6B7280",
    fontWeight: "400",
    textAlign: "center",
    marginBottom: 24,
  },
  formContainer: {
    flex: 1,
    justifyContent: "center",
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
    fontSize: 16,
    color: "#1F2937",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 18,
    fontSize: 16,
    color: "#1F2937",
  },
  showPasswordButton: {
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  showPasswordText: {
    color: "#005F99",
    fontSize: 16,
    fontWeight: "500",
  },
  optionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  rememberContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 4,
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  checkboxChecked: {
    backgroundColor: "#005F99",
    borderColor: "#005F99",
  },
  checkmark: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
  },
  rememberText: {
    color: "#1F2937",
    fontSize: 14,
  },
  forgotPasswordText: {
    color: "#005F99",
    fontSize: 14,
    fontWeight: "500",
  },
  otpContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 320,
    alignSelf: "center",
    marginBottom: 16,
    paddingHorizontal: 10,
  },
  otpInput: {
    width: 45,
    height: 55,
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    fontSize: 20,
    color: "#1F2937",
    fontWeight: "600",
    marginHorizontal: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  otpInputDimmed: {
    backgroundColor: "#F3F4F6",
    borderColor: "#D1D5DB",
    opacity: 0.7,
  },
  otpLabel: {
    color: "#1F2937",
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 16,
  },
  resendButton: {
    alignSelf: "center",
    marginBottom: 16,
  },
  resendText: {
    color: "#005F99",
    fontSize: 14,
    fontWeight: "500",
    textDecorationLine: "underline",
  },
  loginButton: {
    backgroundColor: "#3B82F6", // Blue gradient start
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 25,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  signupLink: {
    alignItems: "center",
    marginBottom: 12,
  },
  signupLinkText: {
    color: "#005F99",
    fontSize: 14,
    fontWeight: "500",
  },
  alternativeLink: {
    alignItems: "center",
    marginBottom: 20,
  },
  alternativeLinkText: {
    color: "#6B7280",
    fontSize: 14,
    fontWeight: "400",
    textDecorationLine: "underline",
  },
  actionLinksContainer: {
    marginBottom: 10,
  },
  actionLinksRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  actionLinkButton: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: 1,
  },
  actionLinkText: {
    color: "#000",
    fontSize: 12,
    fontWeight: "bold",
    textDecorationLine: "underline",
    textAlign: "center",
  },
  alternativeContainer: {
    marginBottom: 20,
  },
  alternativeTitle: {
    color: "#1F2937",
    fontSize: 20,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 24,
  },
  methodButton: {
    backgroundColor: "#3B82F6", // Blue gradient start
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  methodButtonIcon: {
    marginRight: 8,
  },
  methodButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  backToLoginButton: {
    alignItems: "center",
    marginTop: 12,
  },
  backToLoginText: {
    color: "#005F99",
    fontSize: 14,
    fontWeight: "500",
    textDecorationLine: "underline",
  },
  forgotTitle: {
    color: "#1F2937",
    fontSize: 24,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
  },
  forgotSubtitle: {
    color: "#6B7280",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 24,
  },
  methodOption: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  methodOptionSelected: {
    borderColor: "#005F99",
    backgroundColor: "rgba(0, 95, 153, 0.1)",
  },
  methodOptionText: {
    color: "#1F2937",
    fontSize: 16,
    fontWeight: "500",
  },
  statusContainer: {
    marginTop: 10,
    alignItems: "center",
  },
  successStatus: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.3)",
  },
  successText: {
    color: "#10B981",
    fontSize: 16,
    fontWeight: "500",
    marginLeft: 8,
  },
  errorStatus: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
    marginBottom: 20,
  },
  errorText: {
    position: "relative",
    bottom: 20,
    color: "#EF4444",
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
  },
  backendErrorText: {
    color: "#EF4444",
    fontSize: 12,
    marginLeft: 8,
    flex: 1,
  },
  proceedSection: {
    marginTop: 30,
    alignItems: "center",
  },
  countdownText: {
    color: "#6B7280",
    fontSize: 14,
    textAlign: "center",
  },
  errorInput: {
    borderColor: "#EF4444",
    borderWidth: 1,
  },
  // Compact styles for better spacing (light mode)
  compactFormContainer: {
    paddingHorizontal: 20,
  },
  compactTitle: {
    fontSize: 20,
    marginBottom: 8,
  },
  compactSubtitle: {
    fontSize: 14,
    marginBottom: 16,
  },
  compactAlternativeContainer: {
    marginBottom: 16,
  },
  compactMethodOption: {
    paddingVertical: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  compactMethodOptionText: {
    fontSize: 14,
  },
  compactDestinationText: {
    fontSize: 12,
    marginBottom: 0,
    textAlign: 'left',
  },
  compactActionLinks: {
    marginTop: 12,
  },
});

const useThemedStyles = () => {
  const colorScheme = useColorScheme();
  return colorScheme === "dark" ? dark : light;
};

export default useThemedStyles;
